### ISSUE TITLE
[Bug]  Document destructors 

### ISSUE THREAD

**Issue by p-avital** [eclipse-zenoh/zenoh-kotlin#44]
### Describe the bug

Due to the use of destructors which is uncommon in JVM languages, users may get confused as to why their subscribers stop functioning. This needs to be better documented. @da

### To reproduce

N/A

### System info

N/A

**Comment by DariusIMP** [comment]
This issue can be closed, since we took a different approach by associating the lifespan of a session declaration to the lifespan of the session itself, therefore when dropping the declaration, if the session is still alive, then the declaration is still alive as well (the session keeps track of it).
